<?php

return [
    // 1=>'AnswerQuestion',
    1=>'Faq',
    2=>'Article',
    3=>'BarangIo',
    4=>'Buyer',
    5=>'Category',
    6=>'Comment',
    7=>'CompanyHistory',
    8=>'CompanyProfile',
    // 9=>'FaqAnswer',
    // 10=>'FaqQuestion',
    11=>'Feature',
    12=>'ImageBank',
    13=>'Intro',
    14=>'Invoice',
    15=>'LinkTree',
    16=>'Map',
    17=>'Note',
    18=>'PageView',
    19=>'Product',
    20=>'ProductSale',
    21=>'ProductTag',
    22=>'Profile',
    23=>'Response',
    24=>'Sale',
    // 25=>'SpecificationProduct',
    26=>'Stock',
    27=>'Tag',
    28=>'Testimony',
    29=>'User',
    30=>'UserFeature',
    // 'time'=>24*60*60,
    'time'=>60,
];
